services:
  flask-app:
    build: .
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - db-data:/app   # Mounts /app to a persistent volume
      - ./ssl-certs:/app/certs
    environment:
      FLASK_PORT: 443
      SSL_CERT_PATH: /app/certs/fullchain.pem
      SSL_KEY_PATH: /app/certs/privkey.pem
    restart: always

volumes:
  db-data:  # Define a named volume
